apiVersion: v2
appVersion: 9.7.2
dependencies:
- name: traefik
  version: 24.0.0
  repository: https://traefik.github.io/charts
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  tags:
  - postgres
  version: 12.12.4
description: Issue tracker and agile project management platform
home: https://hub.docker.com/r/atlassian/jira-software
icon: https://mox.sh/assets/images/jira-logo.png
keywords:
- jira
- agile
- project management
- issue tracking
- bug tracking
- application
maintainers:
- email: jmox@pm.me
  name: jmox
name: jira-software
sources:
- https://helm.sh
- https://helm.mox.sh
- https://hub.docker.com/r/atlassian/jira-software
type: application
version: 2.7.1
